= Manage your git repos with gall
:icons: font

[quote,Oxford learners dcitionaries]
____
**gall** __noun__

pass:c[/ɡɔːl/]

rude behaviour showing a lack of respect that is surprising because the person behaving badly is not embarrassed synonym impudence

* __Then they had the **gall** to complain!__
* __I almost admired the utter **gall** of the man.__
____

+++<br/>+++
A command line utility to work with multiple Git repositories at a time.

Most of the command line will be following https://git-scm.com/book/en/v2/Git-Internals-Plumbing-and-Porcelain[git porcelain] 
command line interface insofar as it makes sense to `gall`.

So, for those who are already familiar with basic features of git command line, using gall is almost a drop-in experience.
Some of the output of the `gall` will differ significantly from `git`, as Git output does not really make sense in execution scenarios.

To speed up the progress, `gall` will make a reasonable attempt at executing git operations in parallel.

== Status of the project

:warning-icon: 🚧

[WARNING]
**This is very much a Work In Progress effort.**
I am building this tool first and foremost for my own use in order to make something useful and learn Rust in the process.

The features may be incomplete or buggy, progress slow and inconsistent and code can be messy at times.

I do however intend to accept pull requests and have a discussion around implementation details, ux and features that would move this project forward faster.

Do not expect fast feedback cycle however. I do have a life and a job, but I will do my best.


== Git commands implemented:

- [x] `list`    — List all git repositories gall will be operating on
- [ ] `status`  — Fancy status report across multiple repositories
- [ ] `pull`    — Pull changes from remote repository

=== List

List all git repositories `gall` will be operating on.

[source,bash]
gall [OPTIONS] list

=== Status

Show status of multiple repositories.

NOTE: Not implemented

== 
